### PR TITLE
Fix off-by one bug in allele dropping.

### PR DESCRIPTION
**Pull request by caethan**
### Description

GATK 3.6 currently crashes when the number of alleles to drop happens to be equal to the MAX_DROPPED_ALTERNATIVE_ALLELES_TO_LOG constant (=20).  This is thanks to an off-by-one error in the loop conditions that leads to attempting to index too far in the allele HashMap.

This is a simple bug fix that fixes this crashing behavior.

---
### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below. 
#### Content
- [ ] Added or modified tests to cover changes and any new functionality
- [ ] All tests passing on Bamboo (including license tests!)
#### Form
- [x] Rebased, squashed and reworded to produce a single commit (exemptions may be made -- sparingly) that is _uncluttered by excess lines_ (lines that just say "addressed review", "fixed" etc left over from squashing)
- [x] Both the PR and the final rebased commit have a **concise** yet **descriptive** title (they are used when we compile version notes)
- [ ] Edited the README / documentation accordingly and got sign-off from support team (private code is exempt)
#### Review
- [ ] Suggest a reviewer or ask your team lead to suggest one
- [ ] Final (thumbsup) from the reviewer(s)
#### GATK4 Implications
- [ ] If your fix/change is applicable to GATK4 as well, and is reasonably small and self-contained (< ~50 lines or so), port the change to GATK4 and open a PR against https://github.com/broadinstitute/gatk or https://github.com/broadinstitute/gatk-protected as appropriate, or at least make a "best effort" attempt to do so.
- [ ] If your fix/change cannot yet be ported to GATK4 because the tool in question hasn't been ported yet, or has only been partially ported, or it would be difficult/burdensome to port the change, or you tried to port the change and failed, then add the ticket to our list of [GATK3 PRs to be eventually ported to GATK4](https://docs.google.com/document/d/1DjEHw57k5h0i8MZRGYPlQA3InvURKwQ7pCoi_Eigc4M/edit)

Once everything is checked off, you can go ahead and merge the PR. Don't forget to also delete the branch.

### CODE REVIEW

**Comment by vdauwera** [comment]
Hi @caethan, thanks for pointing this out. The team is reviewing your PR and will be in touch shortly.

**Comment by caethan** [comment]
Thanks.  On looking at the problem again, the better and more accurate solution is probably to  switch to `if (allelesToDrop.size() <= MAX_DROPPED_ALTERNATIVE_ALLELES_TO_LOG) {` on the initial if rather than changing the loop conditions.

**Comment by caethan** [comment]
Let me know if you'd like some test data this crashes on, I had I think 3 failed samples out of ~1500.

**Comment by vdauwera** [comment]
Yes, we definitely will need a small test case to add to the test suite.

**Comment by caethan** [comment]
Here's a tarball with the input command, target region, and trimmed alignment file that crashes GATK 3.6.

[test_case.tar.gz](https://github.com/broadgsa/gatk-protected/files/481231/test_case.tar.gz)

**Comment by SHuang-Broad** [comment]
What about replacing the whole if-else block with the following (assuming Java 8 support):

```java
String allelesToDropString  = StringUtil.join(", ", allelesToDrop.stream().limit(MAX_DROPPED_ALTERNATIVE_ALLELES_TO_LOG).collect(Collectors.toList()));
if(allelesToDrop.size() > MAX_DROPPED_ALTERNATIVE_ALLELES_TO_LOG)
    allelesToDropString += " and " + (allelesToDrop.size() - MAX_DROPPED_ALTERNATIVE_ALLELES_TO_LOG) + " more.";
```

**Comment by caethan** [comment]
@vdauwera Is there going to be any movement on this?  This is a clear and obvious bug (that reliably crashes the program!) with a simple fix that has been hanging for at least two months.  I am fixing several other problems with HaplotypeCaller to get it ready for production in our pipeline, and I had planned on putting in pull requests for those fixes as well, but if this is the response I can expect, I just don't see how it is worth my time.

**Comment by vdauwera** [comment]
Hey Brett, very sorry about the delay. Let me check with the dev team -- I know they've been tweaking this code so this may have been done already, but all of that happens in a private development repo (this is just a snapshot repo) so sometimes we forget to update issues in this one.

**Comment by vdauwera** [comment]
@caethan I've discussed this with the devs -- they think the problem should be gone because they rewrote much of the code that handles this. Best thing to do is to check whether you can still reproduce the error with the latest nightly build.

I'm sure you're frustrated with this setup where the code posted here is only a snapshot and does not reflect the latest state of the code. We actually hate it too -- it's a legacy setup from years ago. The good news is that when we switch to GATK4 (~early 2017), it will be a new set of repos (one for fully open-source code, one for license-protected code) where the latest code is posted publicly, so no more of this snapshot crap. You can already check out the new repos at https://github.com/broadinstitute/gatk and https://github.com/broadinstitute/gatk-protected/.

**Comment by caethan** [comment]
OK, thank you for the update.  Unfortunately we can't switch to the nightly builds because we institutionally need the source available (to apply some algorithmic changes and for debugging purposes).  It sounds like bug fix or other pull requests are not going to be useful right now, so we'll come back to this when GATK 4 is in a production-ready state.

**Comment by vdauwera** [comment]
I should add that we do plan to cut a new release (3.7) within the next two weeks, FYI. At that point the latest code will be posted here. After that there will probably be no or minimal further changes as we won't commit any more dev resources to 3.x unless something unexpectedly major comes up.

**Comment by jrandall** [comment]
@caethan just wanted to say thanks for noticing this early and getting the issue raised hopefully in time to make it into 3.7. We just got around to diagnosing GATK 3.6 crashes in 0.4% of our runs and tracked it down to the same bug. We were about to post a PR for it ourselves when we noticed you'd already sorted it all out.

**Comment by vdauwera** [comment]
@jrandall If you have a test case that reproduces the error, could you please run it through the latest nightly build, to confirm that the bug is indeed fixed? As I said earlier we believe it's gone because much of that code has been rewritten, but we don't actually have a test case of our own, so we can't guarantee this corner case isn't still a failure point. If you find that it's still an issue we'll delay the release until this is fixed. Otherwise we're releasing 3.7 by the end of this week.

**Comment by jrandall** [comment]
@vdauwera I have tested HaplotypeCaller on the most recent nightly (`GenomeAnalysisTK-nightly-2016-12-09-g1c2527f`) with an input CRAM that triggers this bug in GATK 3.6 and I can confirm that the error did not occur with the nightly, so this appears to have been fixed. 

To assist with others who may encounter this bug, with GATK 3.6, the stack trace was: 

```
##### ERROR --
##### ERROR stack trace
java.util.NoSuchElementException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1439)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
        at org.broadinstitute.gatk.tools.walkers.haplotypecaller.HaplotypeCallerGenotypingEngine.reduceNumberOfAlternativeAllelesBasedOnLikelihoods(HaplotypeCallerGenotypingEngine.java:336)
        at org.broadinstitute.gatk.tools.walkers.haplotypecaller.HaplotypeCallerGenotypingEngine.assignGenotypeLikelihoods(HaplotypeCallerGenotypingEngine.java:264)
        at org.broadinstitute.gatk.tools.walkers.haplotypecaller.HaplotypeCaller.map(HaplotypeCaller.java:964)
        at org.broadinstitute.gatk.tools.walkers.haplotypecaller.HaplotypeCaller.map(HaplotypeCaller.java:251)
        at org.broadinstitute.gatk.engine.traversals.TraverseActiveRegions$TraverseActiveRegionMap.apply(TraverseActiveRegions.java:709)
        at org.broadinstitute.gatk.engine.traversals.TraverseActiveRegions$TraverseActiveRegionMap.apply(TraverseActiveRegions.java:705)
        at org.broadinstitute.gatk.utils.nanoScheduler.NanoScheduler$ReadMapReduceJob.run(NanoScheduler.java:471)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
##### ERROR ------------------------------------------------------------------------------------------
##### ERROR A GATK RUNTIME ERROR has occurred (version 3.6-0-gf185a75):
##### ERROR
##### ERROR This might be a bug. Please check the documentation guide to see if this is a known problem.
##### ERROR If not, please post the error message, with stack trace, to the GATK forum.
##### ERROR Visit our website and forum for extensive documentation and answers to
##### ERROR commonly asked questions https://www.broadinstitute.org/gatk
##### ERROR
##### ERROR MESSAGE: Code exception (see stack trace for error itself)
##### ERROR ------------------------------------------------------------------------------------------
```

The workaround for this issue will be to upgrade to GATK 3.7 when it is released (or to a recent nightly build).

**Comment by vdauwera** [comment]
Splendid, thanks for confirming, @jrandall!

We're currently grappling with an htsjdk bug that's blocking the 3.7 release, but we might still be able to release today if the gods of the build do us a favor for once. So yeah, Monday then...

**Pull request closed without merging**
